from . import test_edara_branch
from . import test_edara_property
from . import test_edara_lease_contract
from . import test_edara_payment_schedule
from . import test_edara_lease_billing
from . import test_edara_deposit
from . import test_edara_service_charge
from . import test_edara_maintenance_request
from . import test_edara_portal
from . import test_edara_reports
from . import test_edara_dashboard
from . import test_edara_hardening
from . import test_edara_multicompany
from . import test_edara_security_isolation
from . import test_edara_mat015_scoped_accounting
from . import test_edara_renewal_request
from . import test_edara_maintenance_vendor_bill
from . import test_edara_notifications
from . import test_edara_reporting_phase2
from . import test_edara_maintenance_phase2
from . import test_edara_phase7_hardening
from . import test_edara_phase8_currency
from . import test_edara_phase10_lease_engine
from . import test_edara_phase1011_fixes
