from . import test_edara_branch
from . import test_edara_property
from . import test_edara_lease_contract
from . import test_edara_payment_schedule
from . import test_edara_deposit
from . import test_edara_service_charge
from . import test_edara_maintenance_request
from . import test_edara_portal
from . import test_edara_reports
from . import test_edara_dashboard
from . import test_edara_hardening
from . import test_edara_multicompany
