from . import edara_branch
from . import edara_property
from . import edara_building
from . import edara_unit
from . import edara_ownership
from . import edara_lease_contract
from . import edara_payment_schedule_line
from . import edara_deposit
from . import edara_deposit_transaction
from . import edara_service_charge
from . import edara_service_charge_line
from . import edara_maintenance_request
from . import edara_recurring_maintenance
from . import edara_renewal_request
from . import res_partner
from . import res_company
from . import res_config_settings
from . import account_move
from . import account_payment
from . import edara_dashboard
from . import edara_system_field_guard
