from odoo import _, api, fields, models
from odoo.exceptions import ValidationError

EDARA_INVOICE_TYPES = [
    ('rent', 'Rent'),
    ('late_fee', 'Late Fee'),
    ('service_charge', 'Service Charge'),
    ('ad_hoc', 'Ad-hoc'),
]


class AccountMove(models.Model):
    _inherit = 'account.move'

    edara_invoice_type = fields.Selection(EDARA_INVOICE_TYPES, string='EDARA Invoice Type')
    edara_contract_id = fields.Many2one('edara.lease.contract', string='Lease Contract', index=True)

    # Not related fields: a rent/service-charge invoice generated by this module sets
    # these explicitly at create() time (from the contract or service charge line), but
    # a vendor bill (expense) has no contract and the user assigns them directly -
    # see EDARA_PROJECT_STATE.md "Architecture Decisions" for why this changed from
    # related-from-contract fields.
    edara_branch_id = fields.Many2one('edara.branch', string='Branch', index=True)
    edara_property_id = fields.Many2one('edara.property', string='Property', index=True)
    edara_building_id = fields.Many2one('edara.building', string='Building', index=True)
    edara_unit_id = fields.Many2one('edara.unit', string='Unit', index=True)

    @api.onchange('edara_contract_id')
    def _onchange_edara_contract_id(self):
        for move in self:
            if move.edara_contract_id:
                move.edara_unit_id = move.edara_contract_id.unit_id
                move.edara_building_id = move.edara_contract_id.building_id
                move.edara_property_id = move.edara_contract_id.property_id
                move.edara_branch_id = move.edara_contract_id.branch_id

    @api.onchange('edara_property_id')
    def _onchange_edara_property_id(self):
        for move in self:
            if move.edara_property_id:
                move.edara_branch_id = move.edara_property_id.branch_id

    @api.constrains('company_id', 'edara_branch_id', 'edara_property_id', 'edara_building_id', 'edara_unit_id')
    def _check_edara_tags_consistent(self):
        """These are plain editable fields, not related-from-contract (see the
        comment above) - a vendor bill lets the user pick them directly, so
        nothing stops a mismatched or cross-company combination unless checked
        here. Hardening pass (spec §13 "company mismatches"/"branch
        mismatches"/"financial integrity"): the Phase 10 reports aggregate
        revenue/expenses by these tags, so a mismatch would silently corrupt
        another branch's or another company's financial summary."""
        for move in self:
            if move.edara_branch_id and move.edara_branch_id.company_id != move.company_id:
                raise ValidationError(_(
                    "The EDARA Branch on %(move)s belongs to a different company than the journal entry.",
                    move=move.display_name,
                ))
            if move.edara_property_id:
                if move.edara_property_id.company_id != move.company_id:
                    raise ValidationError(_(
                        "The EDARA Property on %(move)s belongs to a different company than the journal entry.",
                        move=move.display_name,
                    ))
                if move.edara_branch_id and move.edara_property_id.branch_id != move.edara_branch_id:
                    raise ValidationError(_(
                        "The EDARA Property on %(move)s does not belong to the selected Branch.",
                        move=move.display_name,
                    ))
            if move.edara_building_id and move.edara_property_id and move.edara_building_id.property_id != move.edara_property_id:
                raise ValidationError(_(
                    "The EDARA Building on %(move)s does not belong to the selected Property.",
                    move=move.display_name,
                ))
            if move.edara_unit_id and move.edara_building_id and move.edara_unit_id.building_id != move.edara_building_id:
                raise ValidationError(_(
                    "The EDARA Unit on %(move)s does not belong to the selected Building.",
                    move=move.display_name,
                ))
